# Generated by Django 4.0.4 on 2022-08-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabricante', models.CharField(max_length=50)),
                ('Modelo', models.URLField(max_length=100)),
                ('HostName', models.URLField(max_length=100, null=True)),
                ('Usuario', models.CharField(max_length=50, null=True)),
                ('Service_Tag', models.CharField(max_length=50)),
                ('Mac_Address', models.CharField(max_length=50)),
                ('IP_Adress', models.CharField(max_length=50)),
                ('Patrimônio', models.CharField(max_length=50)),
                ('Processador', models.CharField(max_length=50)),
                ('Memória', models.CharField(max_length=50)),
                ('HD', models.CharField(max_length=50)),
                ('Setor', models.CharField(max_length=50)),
                ('Sistema_Operacional', models.CharField(max_length=50)),
                ('Fabricante_do_Monitor', models.CharField(max_length=50)),
                ('Patrimônio_do_Monitor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabricante', models.CharField(max_length=50)),
                ('Modelo', models.URLField(max_length=100)),
                ('HostName', models.URLField(max_length=100, null=True)),
                ('Usuario', models.CharField(max_length=50, null=True)),
                ('Licenca', models.CharField(max_length=50)),
                ('Funcao', models.CharField(max_length=50)),
                ('Service_Tag', models.CharField(max_length=50)),
                ('Mac_Address', models.CharField(max_length=50)),
                ('IP_Adress', models.CharField(max_length=50)),
                ('Patrimônio', models.CharField(max_length=50)),
                ('Processador', models.CharField(max_length=50)),
                ('Memória', models.CharField(max_length=50)),
                ('HD', models.CharField(max_length=50)),
                ('Setor', models.CharField(max_length=50)),
                ('Sistema_Operacional', models.CharField(max_length=50)),
                ('Key_Office', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabricante', models.CharField(max_length=50)),
                ('Modelo', models.URLField(max_length=100)),
                ('Service_Tag', models.CharField(max_length=50)),
                ('Setor', models.CharField(max_length=50)),
                ('IP_Address', models.CharField(max_length=50)),
                ('Mac_Address', models.CharField(max_length=50)),
                ('Qtd_de_Portas', models.IntegerField(verbose_name='Quantidade de Portas')),
            ],
        ),
        migrations.CreateModel(
            name='Wyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fabricante', models.CharField(max_length=50)),
                ('Modelo', models.URLField(max_length=100)),
                ('HostName', models.URLField(max_length=100, null=True)),
                ('Service_Tag', models.CharField(max_length=50)),
                ('Mac_Address', models.CharField(max_length=50)),
                ('IP_Adress', models.CharField(max_length=50)),
                ('Patrimonio', models.CharField(max_length=50)),
                ('Setor', models.CharField(max_length=50)),
                ('Fabricante_do_Monitor', models.CharField(max_length=50)),
                ('Patrimonio_do_Monitor', models.CharField(max_length=50)),
            ],
        ),
    ]
