# Generated by Django 4.0.4 on 2022-08-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setor', models.CharField(max_length=100, null=True, verbose_name='Localização do DVR')),
                ('HostName', models.CharField(max_length=100, null=True, verbose_name='Host Name do DVR')),
                ('Fabricante', models.CharField(max_length=50)),
                ('Modelo', models.CharField(max_length=100, null=True, verbose_name='Modelo do DVR')),
                ('Qtd_de_Portas', models.CharField(max_length=10, null=True, verbose_name='Quantidade de Portas')),
                ('HD', models.CharField(max_length=10, verbose_name='Capacidade do HD')),
                ('Mac_Address', models.CharField(max_length=50, verbose_name='Endereço MAC do DVR')),
                ('IP_Address', models.CharField(max_length=50, verbose_name='Endereço IP do DVR')),
                ('Service_Tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='desktop',
            name='HostName',
            field=models.CharField(max_length=100, null=True, verbose_name='Host Name do Desktop'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='IP_Adress',
            field=models.CharField(max_length=50, verbose_name='Endereço IP do Desktop'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Mac_Address',
            field=models.CharField(max_length=50, verbose_name='Endereço MAC do Desktop'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Service_Tag',
            field=models.CharField(max_length=50, verbose_name='Service Tag do Desktop'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='HostName',
            field=models.CharField(max_length=100, null=True, verbose_name='Host Name do Notebook'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='IP_Adress',
            field=models.CharField(max_length=50, verbose_name='Endereço IP do Notebook'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Mac_Address',
            field=models.CharField(max_length=50, verbose_name='Endereço MAC do Notebook'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Service_Tag',
            field=models.CharField(max_length=50, verbose_name='Service Tag do Notebook'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='IP_Address',
            field=models.CharField(max_length=50, verbose_name='Endereço IP do Switch'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='Mac_Address',
            field=models.CharField(max_length=50, verbose_name='Endereço MAC do Switch'),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='HostName',
            field=models.CharField(max_length=100, null=True, verbose_name='Host Name do Wyse'),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='IP_Adress',
            field=models.CharField(max_length=50, verbose_name='Endereço IP do Switch'),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='Mac_Address',
            field=models.CharField(max_length=50, verbose_name='Endereço MAC do Switch'),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='Modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='Service_Tag',
            field=models.CharField(max_length=50, verbose_name='Service Tag do Equipamento'),
        ),
    ]
