# Generated by Django 4.0.4 on 2022-08-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_dvr_alter_desktop_hostname_alter_desktop_ip_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='Modelo',
        ),
        migrations.AddField(
            model_name='desktop',
            name='Modelo_do_Equipamento',
            field=models.CharField(choices=[('MDL', 'ESCOLHA UM DOS MODELOS ABAIXO'), ('3010', 'OPTIPLEX 3010'), ('3020', 'OPTIPLEX 3020'), ('3040', 'OPTIPLEX 3040'), ('3050', 'OPTIPLEX 3050'), ('7010', 'OPTIPLEX 7010'), ('INSP3647', 'INSPIRON 3647'), ('D60', 'POSITIVO MASTER D60'), ('3080', 'OPTIPLEX 3080')], default='MDL', max_length=20),
        ),
    ]
