# Generated by Django 4.0.4 on 2022-08-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_remove_desktop_modelo_desktop_modelo_do_equipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='Fabricante',
        ),
        migrations.AddField(
            model_name='desktop',
            name='Fabricante_do_Equipamento',
            field=models.CharField(choices=[('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD')], max_length=50, null=True, verbose_name='Fabricante do Equipamento'),
        ),
        migrations.AddField(
            model_name='desktop',
            name='Setor_do_Equipamento',
            field=models.CharField(choices=[('RH', 'RECURSOS HUMANOS'), ('TI', 'TEC. DA INFORMAÇÃO'), ('CIND', 'CONTROLES INDUSTRIAIS'), ('MP6', 'MÁQUINA DE PAPEL 6'), ('EXPAP', 'EXPEDIÇÃO DE PAPEL'), ('FAB', 'FABRICAÇÃO DE PAPEL'), ('MANMEC', 'MANUTENÇÃO DE MECÂNICA'), ('PCM', 'PCM MANUTENÇÃO'), ('BIBL', 'BIBLIOTECA'), ('PAF', 'POSTO AVANÇADO FISCAL'), ('ENG', 'ENGENHARIA'), ('PCP', 'PLAN. E CONTROLE DA PRODUÇÃO'), ('SUPRI', 'SUPRIMENTOS')], default='Setor do Equipamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Modelo_do_Equipamento',
            field=models.CharField(choices=[('3010', 'OPTIPLEX 3010'), ('3020', 'OPTIPLEX 3020'), ('3040', 'OPTIPLEX 3040'), ('3050', 'OPTIPLEX 3050'), ('7010', 'OPTIPLEX 7010'), ('INSP3647', 'INSPIRON 3647'), ('D60', 'POSITIVO MASTER D60'), ('3080', 'OPTIPLEX 3080')], max_length=20),
        ),
    ]
