# Generated by Django 4.0.4 on 2022-08-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_remove_desktop_fabricante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktop',
            name='Setor',
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Fabricante_do_Equipamento',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('PHIL', 'PHILIPS')], max_length=50, null=True, verbose_name='Fabricante do Equipamento'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Fabricante_do_Monitor',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('PHIL', 'PHILIPS')], max_length=50, null=True, verbose_name='Fabricante do Monitor'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Patrimônio_do_Monitor',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Setor_do_Equipamento',
            field=models.CharField(choices=[('ESC', 'ESCOLHA UM SETOR'), ('RH', 'RECURSOS HUMANOS'), ('TI', 'TEC. DA INFORMAÇÃO'), ('CIND', 'CONTROLES INDUSTRIAIS'), ('MP6', 'MÁQUINA DE PAPEL 6'), ('EXPAP', 'EXPEDIÇÃO DE PAPEL'), ('FAB', 'FABRICAÇÃO DE PAPEL'), ('MANMEC', 'MANUTENÇÃO DE MECÂNICA'), ('PCM', 'PCM MANUTENÇÃO'), ('BIBL', 'BIBLIOTECA'), ('PAF', 'POSTO AVANÇADO FISCAL'), ('ENG', 'ENGENHARIA'), ('PCP', 'PLAN. E CONTROLE DA PRODUÇÃO'), ('SUPRI', 'SUPRIMENTOS')], max_length=20, verbose_name='Setor do Equipamento'),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='Sistema_Operacional',
            field=models.CharField(choices=[('WIN10', 'WINDOWS 10 64BITS PROFESSIONAL'), ('WIN7', 'WINDOWS 7 64 BITS PROFESSIONAL')], max_length=50, null=True, verbose_name='Sistema operacional do Equipamento'),
        ),
    ]
