# Generated by Django 4.0.4 on 2022-08-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_remove_desktop_setor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='Fabricante',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='Modelo',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='Setor',
        ),
        migrations.AddField(
            model_name='notebook',
            name='Fabricante_do_Equipamento',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('PHIL', 'PHILIPS')], default='Fabricante do Equipamento', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notebook',
            name='Modelo_do_Equipamento',
            field=models.CharField(choices=[('E6430', 'LATITUDE E6430'), ('3420', 'LATITUDE 3420'), ('330-15IKB', 'IDEAPAD 330-15IKB'), ('3468', 'VOSTRO 14 3468'), ('A315-53-3470', 'ASPIRE 3 A315-53-3470'), ('5480', 'LATITUDE 5480'), ('VT5480', 'VOSTRO 5480'), ('HPG7', 'HP 240 G7'), ('3470', 'LATITUDE 3470'), ('VT5481', 'VOSTRO 5481'), ('3400', 'LATITUDE 3400'), ('LTE6430', 'LATITUDE E6430'), ('IPD3470', 'IDEAPAD 330-3470')], default='Modelo do Equipamento', max_length=20),
        ),
        migrations.AddField(
            model_name='notebook',
            name='Setor_do_Equipamento',
            field=models.CharField(choices=[('ESC', 'ESCOLHA UM SETOR'), ('RH', 'RECURSOS HUMANOS'), ('TI', 'TEC. DA INFORMAÇÃO'), ('CIND', 'CONTROLES INDUSTRIAIS'), ('MP6', 'MÁQUINA DE PAPEL 6'), ('EXPAP', 'EXPEDIÇÃO DE PAPEL'), ('FAB', 'FABRICAÇÃO DE PAPEL'), ('MANMEC', 'MANUTENÇÃO DE MECÂNICA'), ('PCM', 'PCM MANUTENÇÃO'), ('BIBL', 'BIBLIOTECA'), ('PAF', 'POSTO AVANÇADO FISCAL'), ('ENG', 'ENGENHARIA'), ('PCP', 'PLAN. E CONTROLE DA PRODUÇÃO'), ('SUPRI', 'SUPRIMENTOS')], default='Setor do Equipamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Sistema_Operacional',
            field=models.CharField(choices=[('WIN10', 'WINDOWS 10 64BITS PROFESSIONAL'), ('WIN7', 'WINDOWS 7 64 BITS PROFESSIONAL')], max_length=50, null=True, verbose_name='Sistema operacional do Equipamento'),
        ),
    ]
