# Generated by Django 4.0.4 on 2022-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_alter_notebook_fabricante_do_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyse',
            name='Fabricante',
        ),
        migrations.RemoveField(
            model_name='wyse',
            name='Setor',
        ),
        migrations.AddField(
            model_name='wyse',
            name='Fabricante_do_Equipamento',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('SAM', 'SAMSUNG'), ('PHIL', 'PHILIPS')], default='FAB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wyse',
            name='Setor_do_Equipamento',
            field=models.CharField(choices=[('ESC', 'ESCOLHA UM SETOR'), ('RH', 'RECURSOS HUMANOS'), ('TI', 'TEC. DA INFORMAÇÃO'), ('CIND', 'CONTROLES INDUSTRIAIS'), ('MP6', 'MÁQUINA DE PAPEL 6'), ('EXPAP', 'EXPEDIÇÃO DE PAPEL'), ('FAB', 'FABRICAÇÃO DE PAPEL'), ('MANMEC', 'MANUTENÇÃO DE MECÂNICA'), ('PCM', 'PCM MANUTENÇÃO'), ('BIBL', 'BIBLIOTECA'), ('PAF', 'POSTO AVANÇADO FISCAL'), ('ENG', 'ENGENHARIA'), ('PCP', 'PLAN. E CONTROLE DA PRODUÇÃO'), ('SUPRI', 'SUPRIMENTOS')], default='ESC', max_length=20),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Fabricante_do_Equipamento',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('SAM', 'SAMSUNG'), ('PHIL', 'PHILIPS')], default='FAB', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Licenca',
            field=models.CharField(choices=[('LVL', 'SELECIONE UM NÍVEL DE LICENÇA'), ('L1', 'LICENCA E1'), ('L2', 'LICENCA E2'), ('L3', 'LICENCA E3')], default='LVL', max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='Sistema_Operacional',
            field=models.CharField(choices=[('SOP', 'SELECIONE UM S.O'), ('WIN10', 'WINDOWS 10 64BITS PROFESSIONAL'), ('WIN7', 'WINDOWS 7 64 BITS PROFESSIONAL')], default='SOP', max_length=50, null=True, verbose_name='Sistema operacional do Equipamento'),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='Fabricante_do_Monitor',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('SAM', 'SAMSUNG'), ('PHIL', 'PHILIPS')], max_length=50, null=True, verbose_name='Fabricante do Monitor'),
        ),
    ]
