# Generated by Django 4.0.4 on 2022-08-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0008_remove_wyse_fabricante_remove_wyse_setor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvr',
            old_name='Setor',
            new_name='Setor_do_Equipamento',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='Setor',
            new_name='Setor_do_Equipamento',
        ),
    ]
