# Generated by Django 4.0.4 on 2022-08-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0009_rename_setor_dvr_setor_do_equipamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setor_do_Equipamento', models.CharField(max_length=100, null=True, verbose_name='Localização do DVR')),
                ('Fabricante_do_Equipamento', models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('HP', 'HEWLETT PACKARD'), ('SAM', 'SAMSUNG')], default='FAB', max_length=50, null=True)),
                ('Modelo_do_Equipamento', models.CharField(choices=[('MODEL', 'MODELO DO EQUIPAMENTO'), ('PWVRTX', 'POWEREDGE VRTX'), ('PWRM630', 'POWEREDGE - M6303'), ('R710', 'POWEREDGE R710'), ('2950', 'POWEREDGE 2950')], default='MODEL', max_length=20)),
                ('IP_Address', models.CharField(max_length=50, verbose_name='Endereço IP do Servidor')),
                ('Patrimonio', models.CharField(max_length=50)),
                ('Service_Tag', models.CharField(max_length=50, verbose_name='Service Tag do Equipamento')),
                ('Memoria', models.CharField(max_length=50)),
                ('HD', models.CharField(max_length=50)),
                ('Sistema_Operacional', models.CharField(choices=[('SOP', 'SELECIONE UM S.O'), ('WINS12', 'WINDOWS SERVER 2012 R2 DATACENTER'), ('WINS08', 'WINDOWS SERVER 2008 R2 ENTERPRISE')], default='SOP', max_length=50, null=True, verbose_name='Sistema operacional do Equipamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='wyse',
            name='Modelo',
        ),
        migrations.AddField(
            model_name='wyse',
            name='Modelo_do_Equipamento',
            field=models.CharField(choices=[('MODEL', 'MODELO DO EQUIPAMENTO'), ('TX0', 'WYSE TX0'), ('SX0', 'WYSE SX0'), ('N10D', 'WYSE N10D')], default='MODEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='wyse',
            name='Fabricante_do_Monitor',
            field=models.CharField(choices=[('FAB', 'ESCOLHA UM FABRICANTE'), ('DLL', 'DELL'), ('ACR', 'ACER'), ('POS', 'POSITIVO'), ('LEN', 'LENOVO'), ('HP', 'HEWLETT PACKARD'), ('AC', 'AOC'), ('SAM', 'SAMSUNG'), ('PHIL', 'PHILIPS')], default='FAB', max_length=50, null=True, verbose_name='Fabricante do Monitor'),
        ),
    ]
