# Generated by Django 4.0.4 on 2022-08-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0010_servidor_remove_wyse_modelo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servidor',
            new_name='Server',
        ),
    ]
